OnYourWay/Controllers/PanelController.cs
using OnYourWay.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace OnYourWay.Controllers
{
    [Authorize(Roles ="Manager")]
    public class PanelController : Controller
    {
        // GET: Panel
        public ActionResult Index()
        {
            using (ApplicationDbContext db=new ApplicationDbContext())
            {
                var admins = db.Users.Where(a => a.Roles.Select(b => b.RoleId).Contains("1")&& a.Roles.Count<2).ToList();
                return View(admins);
            }
           
        }
                            
        public ActionResult Edit(string clientid, string[] accesslevels)
        {
            using (ApplicationDbContext db=new ApplicationDbContext())
            {
                var admin = db.Users.Where(a => a.Id == clientid).FirstOrDefault();
                if (admin!=null)
                {
                    admin.AccessLevel = string.Join(",", accesslevels!=null?accesslevels:new[] {"" ,""});
                }
                db.SaveChanges();
                return Json(new { }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

OnYourWay/Views/Panel/Index.cshtml
@model List<OnYourWay.Models.ApplicationUser>
<html>
<head>
    <title>لوحة تحكم الصفحات</title>
    <style>
        .inputs {
            margin: 4px 0 0;
            margin-top: 1px \9;
            line-height: normal;
            display: inline-block;
            width: auto;
            float: right;
            margin-left: 11px !important;
        }
    </style>
</head>
<body>
    <div class="panel panel-flat">
        <div class="panel-body">
            <div class="container-fluid">
                <div class="clearfix">
                    <div class="row">
                        <input class="form-control" id="client" list="clients" placeholder="اختر مدير" name="client" />
                        <datalist id="clients">
                            @foreach (var item in Model)
                            {
                                <option id="@item.Id" data-user-id="@item.AccessLevel" value="@(item.UserName)" />
                            }
                        </datalist>
                    </div>
                    <br />
                    <br />
                    <div class="row">
                        <div class="col-md-3 col-xs-6">
                            <label class="all-input">
                                الاقسام
                                <input class="inputs" type="checkbox" value="Category" />
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <label class="all-input">
                                شكاوي
                                <input class="inputs" type="checkbox" value="Complain" />
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <label class="all-input">
                                سيارات
                                <input class="inputs" type="checkbox" value="Car" />
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <label class="all-input">
                                مقدم الخدمة
                                <input class="inputs" type="checkbox" value="Client" />
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <label class="all-input">
                                الاشخاص
                                <input class="inputs" type="checkbox" value="Customer" />
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <label class="all-input">
                                المتابعين
                                <input class="inputs" type="checkbox" value="User" />
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <label class="all-input">
                                المديرين
                                <input class="inputs" type="checkbox" value="Admin" />
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <label class="all-input">
                                الرحلات
                                <input class="inputs" type="checkbox" value="Trip" />
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <label class="all-input">
                                الاعدادات
                                <input class="inputs" type="checkbox" value="About" />
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <label class="all-input">
                                المدن
                                <input class="inputs" type="checkbox" value="City" />
                                <span class="checkmark"></span>
                            </label>
                        </div>
                        <div class="col-md-3 col-xs-6">
                            <label class="all-input">
                                الطلبات
                                <input class="inputs" type="checkbox" value="Order" />
                                <span class="checkmark"></span>
                            </label>
                        </div>
                    </div>
                    <br />
                    <br />
                    <br />
                    <br />
                    <div class="row" style="text-align:center;">
                        <button id="SavePanelbtn" class="btn btn-primary" disabled onclick="SavePanel();">حفظ</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        var checkboxsPanel = [];
        function SavePanel() {
            checkboxsPanel = [];
            $("input[type = 'checkbox']").each(function (index) {
                if ($(this).is(':checked')) {
                    checkboxsPanel.push($(this).val());
                   
                }
               
            });
             $.ajax({
                        url: '@Url.Action("Edit","Panel")',
                        type: "POST",
                        dataType: "json",
                        data: {
                            clientid: $('#clients').find('option[value="' + $("#client").val() + '"]').attr('id'),
                            accesslevels: checkboxsPanel
                        },
                        success: function () {
                            location.reload();
                        }
                    });
        }
        $("#client").keyup( function () {
            if ($('#clients').find('option[value="' + $("#client").val() + '"]').val() != undefined) {
                $("#SavePanelbtn").removeAttr('disabled');
                $("input[type = 'checkbox']").each(function (index) {
                    if ($('#clients').find('option[value="' + $("#client").val() + '"]').data("user-id").toLowerCase().includes($(this).val().toLowerCase())) {
                       
                        $(this).attr('checked', true);
                    } else {
                        $(this).removeAttr('checked');
                    }
                });
            } else {
                $("#SavePanelbtn").attr('disabled', true);
            }
        });
        $(document).ready(function () {
           
        })
    </script>
</body>
</html>